services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    networks:
      docker_network:
        ipv4_address: ${TRAEFIK_IP}
      socket_proxy:
        ipv4_address: ${TRAEFIK_PROXY_IP}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker.endpoint=tcp://socket-proxy:${SOCKET_PROXY_PORT}"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
